In [207]:
pip install galois

Note: you may need to restart the kernel to use updated packages.


In [208]:
import galois
import numpy as np
import time

In [209]:
#definisco un campo di Galois come nell'esempio 
field = galois.GF(2**3)

In [210]:
#definisco una matrice k x (n-k) dove n-k = 4
k = 3 #le righe
n_k = 4 #le colonne

#N.B: Less usa q = dimensione campo: 127; k = 126; n = 252 

In [211]:
#ho verificato che funziona pure con i random
#A = field.Random((k, n_k))
#print(A)

#questa è con l'esempio di 4.3
A = field([[1,2,4,7],
           [0,2,3,1],
           [2,3,2,0]])

In [212]:
matrice_bin1 = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
])

matrice_bin1 = field(matrice_bin1)

matrice_bin2 = np.array([
    [1, 0, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
    [0, 1, 0, 0]
])

matrice_bin2 = field(matrice_bin2)

In [213]:
A_primo = field(matrice_bin1 @ A @ matrice_bin2)
print(A_primo)

[[2 0 3 2]
 [1 7 2 4]
 [0 1 2 3]]


In [214]:
A_primo = field([[2,2,0,3],
           [1,4,7,2],
           [0,3,1,2]])

In [215]:
#definito funzione ordinamento lessicografico riga (ordino ogni riga e definisco ordine degli indici) e gestiti casi di 
#conflitto. L'argomento colonne è quello che ci indica in che ordine verificare i conflitti 
#ex: colonne=[0,1,2] --> ordino per colonna 0, se c'è conflitto tra due vedo la colonna 1 e cosi via

#faccio ordinamento crescente dei valori all'interno della riga e torno matrice con righe ordinate (ordinato).
#da questa matrice faccio l'ordinamento elemento a elemento posizionale corrispondente e definisco quindi gli indici 
#riordinati. ex: [1 0 2] --> prima la riga ORIGINALE 1 poi riga ORIGINALE 0 e così via. Per originale intendo "matrice"

def ordina_per_riga(matrice, colonne):
    ordinato = []
    for riga in matrice:
        ordinato.append(np.sort(riga))
        
    ordinato = np.array(ordinato)
    
    #inverto ordine colonne [::-1] poiché lexsort parte dall'ultima colonna
    indici_ordinamento = np.lexsort([ordinato[:, col] for col in colonne[::-1]])
    print("\n",indici_ordinamento)
    print("Matrice ordinata per righe: ",matrice[indici_ordinamento])
    return matrice[indici_ordinamento]

#ordino poi per il primo elemento della colonna e in caso di conflitti li ho gestiti. 
def ordina_per_colonna(matrice, righe):
    indici_ordinamento = np.lexsort([matrice[rig, :] for rig in righe[::-1]])
    return matrice[:, indici_ordinamento]

#qui faccio il test
def test_uguaglianza(matrice1, matrice2):
    colonne = range(n_k)
    righe = range(k)
    print("Matrice1: ", matrice1)

    ordinata1 = ordina_per_colonna(ordina_per_riga(matrice1, colonne), righe)
    print("\nOrdinata 1: ",ordinata1)

    print("Matrice2: ", matrice2)
    ordinata2 = ordina_per_colonna(ordina_per_riga(matrice2, colonne), righe)
    print("\nOrdinata2: ",ordinata2)     

    if np.array_equal(ordinata1, ordinata2):
        print("Le due matrici hanno la stessa CF.")
        return True
    else:
        print("Le due matrici hanno CF diversa")
        return False   



In [216]:
test_uguaglianza(A, A_primo)

Matrice1:  [[1 2 4 7]
 [0 2 3 1]
 [2 3 2 0]]

 [1 2 0]
Matrice ordinata per righe:  [[0 2 3 1]
 [2 3 2 0]
 [1 2 4 7]]

Ordinata 1:  [[0 1 2 3]
 [2 0 3 2]
 [1 7 2 4]]
Matrice2:  [[2 2 0 3]
 [1 4 7 2]
 [0 3 1 2]]

 [2 0 1]
Matrice ordinata per righe:  [[0 3 1 2]
 [2 2 0 3]
 [1 4 7 2]]

Ordinata2:  [[0 1 2 3]
 [2 0 3 2]
 [1 7 2 4]]
Le due matrici hanno la stessa CF.


True